### ISSUE TITLE
South Africa coverage request: Orms, cameraland, Fotodiscountworld, outdoorphoto.

### ISSUE THREAD

**Issue by Arf9999** [datawookie/retail#13]
Request to add weekly coverage of the following sites:

Orms:   https://ormsdirect.co.za/
Cameraland: https://www.cameraland.co.za/
Outdoorphoto: https://outdoorphoto.co.za/
Fotodiscountworld: https://www.fotodiscountworld.co.za/

**Comment by datawookie** [comment]
Thanks for the suggestions, @Arf9999. I'll add them to my backlog. Can't promise when they'll be ready, but I'd hope to have them in staging within a week or so and hopefully in production some time during April.
