### ISSUE TITLE
Feature request: standardise variable naming across returned dataframes.

### ISSUE THREAD

**Issue by Arf9999** [datawookie/retail#4]
This is not a bug, but a suggestion:

In order to simplify joining of data.frames, it would be better if:

1. `retailer()` returned an id column named "retailer_id", and
2. `product()` returned an id column named "product_id", 
rather than both simply having an index column called "id"

That would make the column names more consistent across `product()`, `retailer()`, and `product_prices()`.

**Comment by datawookie** [comment]
Thanks for the suggestion, @Arf9999.

Fixed by #5.
